name: Update gist with WakaTime stats
on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@next-7
      - name: Install dependencies
        run: pnpm i
      - name: Update gist
        env:
          GIST_ID: 901b17c5d7cc0a34c3c509995b5c05ca
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: node index.mjs
